#!/bin/bash

. ../00_template/template

function mysystem_info()
{
	if [ $# -eq 0 ]; then
		echo -e "Informacje systemowe ---> Nook Info <---
	all	- wyszystkie informacje
	linux	- informacje o dystrybucji systemu
	res	- rozdzielczość ekranu
	user	- zdefinowani użytkownicy\n"
	fi
	for argInfo in "$@"
	do
		case $argInfo in
			'all') mysystem_info linux res user ;;
			'linux') echo -e "${GREEN}Dystrybucja: $NC"$( lsb_release -d | awk -F: '{printf "%s\n",$2}' ) ;;
			'res') echo -en "${GREEN}Rozdzielczość: $NC"; xrandr | grep '*' | awk -F' ' '{printf "%s\n",$1}' ;;
			'user') echo -e "${GREEN}Zdefiniowani użytkownicy: $NC" 
				awk -F: '($3 >= 1000 && $3 < 65534) {printf "%s:%s:%s:%s\n",$1,$3,$6,$7}' /etc/passwd ;;
			*) echo -e "${RED}[ERROR] - Nie rozpoznaje argumenu!$NC" | tee -a log_$currentDate.log
		esac
	done
}

function main()
{
	mysystem_info $@
}

main $@
